export const brandOptions = [
  { label: 'Essence', value: 'Essence' },
  { label: 'Glamour Beauty', value: 'Glamour Beauty' },
  { label: 'Velvet Touch', value: 'Velvet Touch' },
  { label: 'Chic Cosmetics', value: 'Chic Cosmetics' },
  { label: 'Calvin Klein', value: 'Calvin Klein' },
  { label: 'Chanel', value: 'Chanel' },
  { label: 'Dior', value: 'Dior' },
  { label: 'Gucci', value: 'Gucci' },
  { label: 'Dolce & Gabbana', value: 'Dolce & Gabbana' },
  { label: 'Apple', value: 'Apple' },
  { label: 'Samsung', value: 'Samsung' },
  { label: 'Huawei', value: 'Huawei' },
  { label: 'OPPO', value: 'OPPO' },
  { label: 'Microsoft', value: 'Microsoft' },
  { label: 'HP', value: 'HP' },
  { label: 'Lenovo', value: 'Lenovo' },
  { label: 'Asus', value: 'Asus' },
  { label: 'Acer', value: 'Acer' },
  { label: 'Dell', value: 'Dell' },
  { label: 'Infinix', value: 'Infinix' },
  { label: 'Rolex', value: 'Rolex' },
  { label: 'Casio', value: 'Casio' },
  { label: 'Nike', value: 'Nike' },
  { label: 'Adidas', value: 'Adidas' },
  { label: 'Puma', value: 'Puma' },
  { label: 'Under Armour', value: 'Under Armour' }
];