export const categoryOptions = [
    { label: 'Красота', value: 'beauty' },
    { label: 'Парфюмерия', value: 'fragrances' },
    { label: 'Мебель', value: 'furniture' },
    { label: 'Продукты', value: 'groceries' },
    { label: 'Декор для дома', value: 'home-decoration' },
    { label: 'Кухонные аксессуары', value: 'kitchen-accessories' },
    { label: 'Ноутбуки', value: 'laptops' },
    { label: 'Мужские рубашки', value: 'mens-shirts' },
    { label: 'Мужская обувь', value: 'mens-shoes' },
    { label: 'Мужские часы', value: 'mens-watches' },
    { label: 'Аксессуары для телефонов', value: 'mobile-accessories' },
    { label: 'Мотоциклы', value: 'motorcycle' },
    { label: 'Уход за кожей', value: 'skin-care' },
    { label: 'Смартфоны', value: 'smartphones' },
    { label: 'Спортивные аксессуары', value: 'sports-accessories' },
    { label: 'Солнцезащитные очки', value: 'sunglasses' },
    { label: 'Планшеты', value: 'tablets' },
    { label: 'Футболки и топы', value: 'tops' },
    { label: 'Транспорт', value: 'vehicle' },
    { label: 'Женские сумки', value: 'womens-bags' },
    { label: 'Женские платья', value: 'womens-dresses' },
    { label: 'Женские украшения', value: 'womens-jewellery' },
    { label: 'Женская обувь', value: 'womens-shoes' },
    { label: 'Женские часы', value: 'womens-watches' }
];